### ISSUE TITLE
Dataset process

### ISSUE THREAD

**Issue by DingYikang** [xxlong0/ESTDepth#1]
Hi~ 
Thanks a lot for your excellent work! I'm wondering what pre-processing work should do for Scannet dataset if I want to retrain this model ? Have you ever processed the Scannet dataset?
Thanks!

**Comment by flamehaze1115** [comment]
We don't do any preprocessing operations for ScanNet, and just sample frames from the original video sequences.

**Comment by DingYikang** [comment]
> We don't do any preprocessing operations for ScanNet, and just sample frames from the original video sequences.

Got it~ Thanks!!

**Comment by flamehaze1115** [comment]
closed.
