### ISSUE TITLE
Testing on TUM-RGB-SLAM Dataset

### ISSUE THREAD

**Issue by aakash26** [xxlong0/ESTDepth#2]
Hi Authors,

Thanks for providing the code and all information. I would like to test on TUM-RGB-SLAM Dataset or any other custom dataset that can be found. I understand that we require RGB images, camera poses, camera intrinsic parameters for testing on any video sequence. How do we test with the given eval-script as when I go through the script it's only coded for Scannet or 7Net.
Is it possible to provide a test-script for other datasets?

Thanks and Regards
Aakash Rajpal

**Comment by xxlong0** [comment]
The provided script is only related to the data format which you store as. Just keep the data format of TMU the same as 7scenes.

**Comment by flamehaze1115** [comment]
Closed, since no further responses.
