### ISSUE TITLE
Calibration of 7-Scenes datasets

### ISSUE THREAD

**Issue by ckLibra** [xxlong0/ESTDepth#3]
Hi, thanks for your great work! I'm wondering whether the 7-Scenes datasets have been calibrated before evaluation or just use the raw data from the official website for evaluation?

**Comment by xxlong0** [comment]
Following prior works, the depth maps are not calibrated before evaluation.
You can do the evaluation and test.

andy cheng ***@***.***>于2021年8月21日 周六20:47写道：

**Comment by xxlong0** [comment]
Typo. You can do the calibration and then reevaluate all prior works.

Long, Xiaoxiao ***@***.***>于2021年8月22日 周日22:04写道：

**Comment by ckLibra** [comment]
Thanks for your reply!
