### ISSUE TITLE
Is depth prediction results scaled or not?

### ISSUE THREAD

**Issue by kudo1026** [xxlong0/ESTDepth#5]
Hi,

Thanks for the great work! One question: is your depth prediction result scaled with ground truth depth or not? Looking at your `evaluate_depth` function in `metric.py`, it seems you calculated both. But are the numbers (e.g. table 1) in your paper gt-scaled or not?

Thanks!

**Comment by flamehaze1115** [comment]
In the paper, we use gt depth, not gt_scaled depth.
